#!/usr/bin/env ruby

vedro_red = 50
vedro_green = 100
vedro_blue = 30
vedro_yellow = 60

values_array = [50, 100, 30, 60]
maxval = values_array.max

 case maxval
  when 50
    color = "red"
  when 100
    color ="green"
  when 30
    color ="blue"
  else
    color ="yellow"
end

puts "The maximum numbers of balls has a bucket with " +  color + " color"


if vedro_green > vedro_yellow
  puts "The green bucket contains more balls"
else
  puts "The yellow bucket contains more balls"
end

if vedro_green > vedro_red + vedro_blue
  puts "The green bucket contains more balls"
else
  puts "The red and yellow buckets contain more balls than green"
end




